version: '3'
name: "vis"
services:
  rr:
    build: ./gobgp
    networks:
      main:
        ipv4_address: 10.10.0.1
    env_file:
      - "rr.env"

  client:
    build: ./gobgp
    networks:
      main:
    env_file:
      - "client.env"

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
          ip_range: 10.10.0.0/24
          gateway: 10.10.0.254
