version: '3'
name: "vis"
services:
  rr:
    build: ./gobgp
    init: true
    networks:
      main:
        ipv4_address: 10.10.0.1
    env_file:
      - "rr.env"

  client:
    build: ./gobgp
    depends_on: 
      - rr
    init: true
    networks:
      main:
    environment:
      - REPLICA={{.Task.Slot}}
    env_file:
      - "client.env"
    deploy:
      replicas: 1

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
          ip_range: 10.10.0.0/24
          gateway: 10.10.0.254
